In [144]:
import pandas as pd
movdf=pd.read_csv("tmdb_movies.csv")
creditdf=pd.read_csv("tmdb_credits.csv")

In [48]:

#movdf.rename(columns={"id":"movie_id"},inplace=True)
#movdf['tagline'].head(5)

0                       Enter the World of Pandora.
1    At the end of the world, the adventure begins.
2                             A Plan No One Escapes
3                                   The Legend Ends
4              Lost in our world, found in another.
Name: tagline, dtype: object

In [145]:
#tmdb=pd.merge(movdf,creditdf,on='movie_id')
tmdb=pd.merge(movdf,creditdf,on='title')
final_df=tmdb[['genres','title','id','overview','keywords','cast','crew']]
final_df.head(5)

,genres,title,id,overview,keywords,cast,crew
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Avatar,19995,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Spectre,206647,A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Dark Knight Rises,49026,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",John Carter,49529,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [146]:
final_df.isnull().sum()
final_df.dropna(inplace=True)

C:\Users\user\AppData\Local\Temp\ipykernel_2648\3115023090.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace=True)

In [70]:
#genre_str=final_df.iloc[0][0]
#import json
#genrlist=json.loads(genre_str)
#list_genre=[item['name'] for item in genrlist]

C:\Users\user\AppData\Local\Temp\ipykernel_2648\221142905.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  genre_str=final_df.iloc[0][0]

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [86]:
# import json
# def genre_name(genre_str):
#     genre_list = json.loads(genre_str)
#     # return ','.join([item['name'] for item in genre_list])
#     return [item['name'] for item in genre_list]

# final_df['genres'] = final_df['genres'].apply(genre_name)
try:
        if pd.isna():
            return []
            except(TypeError, SyntaxError,ValueError) as e:
        return []

"\nimport json\ndef genre_name(genre_str):\n    genre_list=json.loads(genre_str)\n    #return ','.join([item['name'] for item in genre_list])\n    return [item['name'] for item in genre_list]\n\nfinal_df['genres']=final_df['genres'].apply(genre_name)\n"

In [147]:
import ast
import pandas as pd

def convert(obj):
    try:
        if pd.isna(obj):
            return []

        # Only parse if it's a string
        if isinstance(obj, str):
            genre_list = ast.literal_eval(obj)
        elif isinstance(obj, list):  # Already a list
            genre_list = obj
        else:
            return []

        return [item['name'] for item in genre_list if 'name' in item]

    except (TypeError, SyntaxError, ValueError) as e:
        print(f"Error: {e} — Data: {obj}")
        return []

# Apply to column
final_df['genres'] = final_df['genres'].apply(convert)

C:\Users\user\AppData\Local\Temp\ipykernel_2648\2400174178.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['genres'] = final_df['genres'].apply(convert)

In [126]:
final_df.head(10)

,genres,title,id,overview,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,19995,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",Spectre,206647,A cryptic message from Bond’s past sends him o...,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,49026,Following the death of District Attorney Harve...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",John Carter,49529,"John Carter is a war-weary, former military ca...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
5,"[Fantasy, Action, Adventure]",Spider-Man 3,559,The seemingly invincible Spider-Man goes up ag...,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...","[{""cast_id"": 30, ""character"": ""Peter Parker / ...","[{""credit_id"": ""52fe4252c3a36847f80151a5"", ""de..."
6,"[Animation, Family]",Tangled,38757,When the kingdom's most wanted-and most charmi...,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...","[{""cast_id"": 34, ""character"": ""Flynn Rider (vo...","[{""credit_id"": ""52fe46db9251416c91062101"", ""de..."
7,"[Action, Adventure, Science Fiction]",Avengers: Age of Ultron,99861,When Tony Stark tries to jumpstart a dormant p...,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...","[{""cast_id"": 76, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""55d5f7d4c3a3683e7e0016eb"", ""de..."
8,"[Adventure, Fantasy, Family]",Harry Potter and the Half-Blood Prince,767,"As Harry begins his sixth year at Hogwarts, he...","[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...","[{""cast_id"": 3, ""character"": ""Harry Potter"", ""...","[{""credit_id"": ""52fe4273c3a36847f801fab1"", ""de..."
9,"[Action, Adventure, Fantasy]",Batman v Superman: Dawn of Justice,209112,Fearing the actions of a god-like Super Hero l...,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...","[{""cast_id"": 18, ""character"": ""Bruce Wayne / B...","[{""credit_id"": ""553bf23692514135c8002886"", ""de..."

In [148]:
final_df['keywords']=final_df['keywords'].apply(convert)
final_df.head(5)

C:\Users\user\AppData\Local\Temp\ipykernel_2648\3454864246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['keywords']=final_df['keywords'].apply(convert)

,genres,title,id,overview,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,19995,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",Spectre,206647,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,49026,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",John Carter,49529,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [149]:
import ast
final_df['cast'][0]
def cast_convert(obj):
    L=[]
    counter=0
    if counter!=3:
        genre_list=ast.literal_eval(obj)
        for item in genre_list:
            L.append(item['name'])
            counter+=1
    return L
final_df['cast']=final_df['cast'].apply(cast_convert)
final_df.head(5)

C:\Users\user\AppData\Local\Temp\ipykernel_2648\4217070284.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['cast']=final_df['cast'].apply(cast_convert)

,genres,title,id,overview,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,19995,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,"[Action, Adventure, Crime]",Spectre,206647,A cryptic message from Bond’s past sends him o...,"[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,49026,Following the death of District Attorney Harve...,"[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,"[Action, Adventure, Science Fiction]",John Carter,49529,"John Carter is a war-weary, former military ca...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [152]:

def crew_convert(obj):
    L=[]
    crew_list=ast.literal_eval(obj)
    for item in crew_list:
        if item['job']=="Director":
            L.append(item['name'])
    return L
final_df['crew']=final_df['crew'].apply(crew_convert)
final_df['crew'].head(4)

C:\Users\user\AppData\Local\Temp\ipykernel_2648\2457488337.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['crew']=final_df['crew'].apply(crew_convert)

0        [James Cameron]
1       [Gore Verbinski]
2           [Sam Mendes]
3    [Christopher Nolan]
Name: crew, dtype: object

In [153]:
final_df.head(2)

,genres,title,id,overview,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,19995,"In the 22nd century, a paraplegic Marine is di...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]

In [154]:
final_df['overview']=final_df['overview'].apply(lambda item:item.split())
final_df.head(5)

C:\Users\user\AppData\Local\Temp\ipykernel_2648\522168370.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['overview']=final_df['overview'].apply(lambda item:item.split())

,genres,title,id,overview,keywords,cast,crew
0,"[Action, Adventure, Fantasy, Science Fiction]",Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,"[Action, Adventure, Crime]",Spectre,206647,"[A, cryptic, message, from, Bond’s, past, send...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux, R...",[Sam Mendes]
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,"[Action, Adventure, Science Fiction]",John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [165]:
final_df['genres']=final_df['genres'].apply(lambda x: [item.replace(" ","") for item in x])
final_df['cast']=final_df['cast'].apply(lambda x: [item.replace(" ","") for item in x])
final_df['crew']=final_df['crew'].apply(lambda x: [item.replace(" ","") for item in x])
final_df['keywords']=final_df['keywords'].apply(lambda x: [item.replace(" ","") for item in x])

C:\Users\user\AppData\Local\Temp\ipykernel_2648\1762854905.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['genres']=final_df['genres'].apply(lambda x: [item.replace(" ","") for item in x])
C:\Users\user\AppData\Local\Temp\ipykernel_2648\1762854905.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['cast']=final_df['cast'].apply(lambda x: [item.replace(" ","") for item in x])
C:\Users\user\AppData\Local\Temp\ipykernel_2648\1762854905.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['crew']=final_df['crew'].apply(lambda x: [item.replace(" ","") for item in x])
C:\Users\user\AppData\Local\Temp\ipykernel_2648\1762854905.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['keywords']=final_df['keywords'].apply(lambda x: [item.replace(" ","") for item in x])

In [162]:
#code to remove blank/whitespace from list of string
L=["Action", "Adventure", "Fantasy", "Science Fiction"]
newL=[item.replace(" ","") for item in L]
print(newL)

['Action', 'Adventure', 'Fantasy', 'ScienceFiction']

In [166]:
final_df.head(5)

,genres,title,id,overview,keywords,cast,crew
0,"[Action, Adventure, Fantasy, ScienceFiction]",Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,"[Action, Adventure, Crime]",Spectre,206647,"[A, cryptic, message, from, Bond’s, past, send...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,"[Action, Crime, Drama, Thriller]",The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,"[Action, Adventure, ScienceFiction]",John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [175]:
final_df['tags']=final_df['overview']+final_df['genres']+final_df['keywords']+final_df['cast']+final_df['crew']

C:\Users\user\AppData\Local\Temp\ipykernel_2648\2052554498.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['tags']=final_df['overview']+final_df['genres']+final_df['keywords']+final_df['cast']+final_df['crew']

In [176]:
final_df.head(2)

,genres,title,id,overview,keywords,cast,crew,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]",Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]",Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."

In [181]:
recom_df=final_df[['id','tags','title']]
recom_df['tags']=recom_df['tags'].apply(lambda x: " ".join(x))
recom_df['tags']=recom_df['tags'].apply(lambda x: x.lower())

C:\Users\user\AppData\Local\Temp\ipykernel_2648\2393177564.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recom_df['tags']=recom_df['tags'].apply(lambda x: " ".join(x))
C:\Users\user\AppData\Local\Temp\ipykernel_2648\2393177564.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recom_df['tags']=recom_df['tags'].apply(lambda x: x.lower())

In [182]:
recom_df.head(3)

,id,tags,title
0,19995,"in the 22nd century, a paraplegic marine is di...",Avatar
1,285,"captain barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End
2,206647,a cryptic message from bond’s past sends him o...,Spectre

In [231]:
#from sklearn.feature_extraction.text import CountVectroizer
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')
vector=cv.fit_transform(recom_df['tags']).toarray()
cv.get_feature_names_out()
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
def stem_tag(text):
    L=[]
    for item in text.split():
        L.append(ps.stem(item))
    return " ".join(L)
recom_df['tags']=recom_df['tags'].apply(stem_tag)

C:\Users\user\AppData\Local\Temp\ipykernel_2648\3036244385.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  recom_df['tags']=recom_df['tags'].apply(stem_tag)

In [232]:
from sklearn.metrics.pairwise import cosine_similarity

In [233]:
similarity=cosine_similarity(vector)

In [220]:
sorted(list(enumerate(similarity[2])),reverse=True,key=lambda x:x[1])[1:6]

[(29, 0.36980013081681934),
 (11, 0.36440544440674755),
 (1344, 0.3200921998322399),
 (3164, 0.2611164839335468),
 (4075, 0.25607375986579195)]

In [239]:
def recommend(movie):
    mov_ind=recom_df[recom_df['title']==movie].index[0]
    distance_mov=similarity[mov_ind]
    mov_list=sorted(list(enumerate(distance_mov)),reverse=True,key=lambda x:x[1])[1:6]
    for i in mov_list:
        print(recom_df.iloc[i[0]].title)

In [240]:
recommend('Avatar')

Aliens vs Predator: Requiem
Predator
Battle: Los Angeles
Falcon Rising
Independence Day